// By: Eric MacDonald (eMac)

import {
	Button,
	VerticalBox
} from "std-widgets.slint";

export component IconButton {
	in property icon <=> button_icon.source;
	in property <string> tooltip: "";
	callback pointer-event(PointerEvent);
    callback clicked <=> clickable-area.clicked;

	z: 1;

	displayed-button := Button {
		width: 100%;
		height: 100%;
		opacity: clickable-area.has-hover ? 1.00 : 0.80;
	}
	clickable-area := TouchArea {
		width: 100%;
		height: 100%;
		pointer-event(event) => {
			if event.kind == PointerEventKind.down {
				displayed-button.checked = true;
			} else if event.kind == PointerEventKind.up {
				displayed-button.checked = false;

				if event.button == PointerEventButton.left {
					root.clicked();
				}
			}
			
			root.pointer-event(event);
		}

		button-icon-layout := HorizontalLayout {
			z: 1;
			spacing: 0px;
			alignment: space-around;
			padding: root.padding;

			button-icon := Image {
				z: 1;
				opacity: clickable-area.has-hover ? 1.00 : 0.80;
				preferred-height: icon.height * 1px;
				preferred-width: icon.width * 1px;
			}  
		}

		button-tooltip := Rectangle { 
			states [ 
				visible when self.visible: {
					opacity: 0.8; 
					in {
						animate opacity {
							duration: 275ms;
							delay: 700ms;
						}
					}
				}
			]
			x: parent.mouse-x;
			y: parent.mouse-y - self.height;
			z: 1;
			width: tooltip-layout.preferred-width;
			height: tooltip-layout.preferred-height;
			visible: parent.has-hover && root.tooltip != "";
			opacity: 0.0;
			background: #000;
			border-width: 1px;
			border-radius: 4px;
			border-color: #444;
	
			tooltip-layout := HorizontalLayout { 
				z: 1;
				padding: 6px;
				Text { 
					z: 1;
					max-width: 500px;
					overflow: elide;
					text: root.tooltip;
				}
			}
		}
	}
}