// By: Eric MacDonald (eMac)

import {
	Page
} from "./widgets/page.slint";
import { 
	HorizontalBox,
	Button,
	Switch,
	Palette
} from "std-widgets.slint";
import {
	EditableComboBox,
	HintedItem
} from "./widgets/editablecombobox.slint";
import {
	TitledVerticalBox,
	TitledHorizontalBox
} from "./widgets/titledbox.slint";
import {
	IconButton
} from "./widgets/iconbutton.slint";

export enum BuildImportState {
	ImportUnavailable,
	WillReplace,
	WillCreate
}

export global UIMAMEOptions {


	// Selected Box
	in-out property<[HintedItem]> selectable_boxes: [];
	in-out property<string> selected_box: "";

	// Selected ROM->BootROM
	in-out property<[HintedItem]> selectable_bootroms: [];
	in-out property<string> selected_bootrom: "";
	in-out property<int> selected_bootrom_index: 0;
	in-out property<BuildImportState> bootrom_import_state: BuildImportState.ImportUnavailable;

	// Selected ROM->AppROM
	in-out property<bool> uses_disk_approms: false;
	in-out property<bool> uses_mdoc_approms: false;
	in-out property<bool> can_choose_hdimg: false;
	in-out property<[HintedItem]> selectable_approms: [];
	in-out property<string> selected_approm: "";
	in-out property<string> selected_hdimg_path: "";
	in-out property<bool> selected_hdimg_enabled: false;
	in-out property<bool> can_revert_approm: false;
	in-out property<BuildImportState> approm_import_state: BuildImportState.ImportUnavailable;

	// Selected ROM->SSID->Manufacture
	in-out property<string> ssid-in-file: ""; // used to detect if someone typed a custom SSID. Custom SSIDs are only saved to file when someone starts MAME.
	in-out property<[HintedItem]> selectable_ssids: []; // not used but can be in the future.
	in-out property<string> selected_ssid: "";
	in-out property<[HintedItem]> selectable_ssid_manufactures: [];
	in-out property<string> selected_ssid_manufacture: "";

	// Selected Modem
	in-out property<[HintedItem]> selectable_modem_bitb_endpoints: [
		{
			hint: "Local TouchPPP Server",
			value: "127.0.0.1:1122"
		},
		{
			hint: "eMac's Public TouchPPP Server",
			value: "wtv.ooguy.com:1122"
		}
	];
	in-out property<string> selected_modem_bitb_endpoint: "127.0.0.1:1122";
	in-out property<[HintedItem]> selectable_modem_bitb_startpoints: [];
	in-out property<string> selected_modem_bitb_startpoint: "";

	// Debug Console
	in-out property<[HintedItem]> selectable_debug_bitb_endpoints: [
		{
			hint: "",
			value: "Launcher Console"
		},
		{
			hint: "Local ser2net",
			value: "127.0.0.1:2000"
		},
	];
	in-out property<string> selected_debug_bitb_endpoint: "Launcher Console";
	in-out property<[HintedItem]> selectable_debug_bitb_startpoints: [];
	in-out property<string> selected_debug_bitb_startpoint: "";

	// Other Options
	in-out property<bool> verbose_mode: false;
	in-out property<bool> windowed_mode: true;
	in-out property<bool> use_drc: true;
	in-out property<bool> debug_mode: false;
	in-out property<bool> skip_info_screen: true;
	in-out property<bool> disable_mouse_input: true;
	in-out property<bool> console_input: false;
	in-out property<bool> disable_sound: false;

	// Custom options
	in-out property<string> custom_options: "";

	callback select-box();
	callback select-bootrom();
	callback select-approm();
	callback import-bootrom();
	callback import-approm();
	callback revert-approm();
	callback choose-hdimg();
	callback unset-hdimg();
	callback generate-ssid();
	callback start-mame();
}

export component StartPage inherits Page {
	z: 1;

	TitledHorizontalBox {
		title: @tr("Selected Box");

		EditableComboBox {
			hintedmodel: UIMAMEOptions.selectable_boxes;
			current-value <=> UIMAMEOptions.selected_box;
			selection-changed => {
				UIMAMEOptions.select-box();
			}
		}
	}

	TitledHorizontalBox {
		title: @tr("Selected ROM");
		box-spacing: 5px;
		z: 1;

		bootrom-section := VerticalLayout {
			width: 30%;
			spacing: 2px;
			z: 2;
			Text {
				text: @tr("BootROM Build");
			}
			EditableComboBox {
				hintedmodel: UIMAMEOptions.selectable_bootroms;
				current-value <=> UIMAMEOptions.selected_bootrom;
				height: 34px;
				selection-changed => {
					UIMAMEOptions.select-bootrom();
				}
			}
			Button {
				visible: UIMAMEOptions.bootrom_import_state != BuildImportState.ImportUnavailable;
				text: (UIMAMEOptions.bootrom_import_state == BuildImportState.WillCreate) ? @tr("Import Build") : @tr("Replace Build");
				height: 34px;
				clicked => {
					UIMAMEOptions.import-bootrom();
				}
			}
		}

		approm-section := VerticalLayout {
			width: 30%;
			spacing: 2px;
			z: 1;
			Text {
				text: @tr("AppROM Build");
			}
			HorizontalLayout {
				spacing: 2px;
				IconButton {
					width: (UIMAMEOptions.can_choose_hdimg) ? 32px : 0px;
					height: 34px;
					padding: 3px;
					z: 3;
					icon: (UIMAMEOptions.selected_hdimg_path == "") ? @image-url("images/hd-img-inactive.svg") : @image-url("images/hd-img-active.svg");
					tooltip: (UIMAMEOptions.selected_hdimg_path == "") ? "Choose Disk Image" : "\{UIMAMEOptions.selected_hdimg_path}\nRight click to remove";
					pointer-event(event) => {
						if event.kind == PointerEventKind.up {
							if event.button == PointerEventButton.left {
								UIMAMEOptions.choose-hdimg();
							} else if event.button == PointerEventButton.right {
								UIMAMEOptions.unset-hdimg();
							}
						}
					}
				}
				EditableComboBox {
					hintedmodel: UIMAMEOptions.selectable_approms;
					current-value <=> UIMAMEOptions.selected_approm;
					height: 34px;
					selection-changed => {
						UIMAMEOptions.select-approm();
					}
				}
				IconButton {
					width: (UIMAMEOptions.can_revert_approm) ? 32px : 0px;
					height: 34px;
					padding: 3px;
					icon: @image-url("images/revert-approm.svg");
					tooltip: "Revert Preset Image";
					clicked => {
						UIMAMEOptions.revert-approm();
					}
				}
			}
			Button {
				visible: UIMAMEOptions.approm_import_state != BuildImportState.ImportUnavailable;
				text: (UIMAMEOptions.approm_import_state == BuildImportState.WillCreate) ? @tr("Import Build") : @tr("Replace Build");
				height: 34px;
				clicked => {
					UIMAMEOptions.import-approm();
				}
			}
		}

		ssid-section := VerticalLayout {
			width: (parent.width * 0.4) - 10px;
			spacing: 2px;
			Text {
				text: @tr("SSID (DS2401 ROM)");
			}
			EditableComboBox {
				hintedmodel: UIMAMEOptions.selectable_ssids;
				current-value <=> UIMAMEOptions.selected_ssid;
				editable: true;
				height: 34px;
			}
			HorizontalLayout {
				width: 100%;
				spacing: 2px;
				EditableComboBox {
					hintedmodel: UIMAMEOptions.selectable_ssid_manufactures;
					current-value <=> UIMAMEOptions.selected_ssid_manufacture;
					width: 60%;
					height: 34px;
				}
				Button {
					text: @tr("Generate");
					width: (parent.width * 0.4) - 4px;
					height: 34px;
					padding: 0px;
					clicked => {
						UIMAMEOptions.generate-ssid();
					}
				}
			}
		}
	}

	TitledHorizontalBox {
		title: @tr("Selected Modem");

		HorizontalLayout {
			EditableComboBox {
				visible: (UIMAMEOptions.selectable_modem_bitb_startpoints.length > 1);
				width: (UIMAMEOptions.selectable_modem_bitb_startpoints.length > 1) ? 30% : 0%;
				enabled: UIMAMEOptions.selectable_modem_bitb_startpoints.length > 1;
				editable: false;
				hintedmodel: UIMAMEOptions.selectable_modem_bitb_startpoints;
				current-value <=> UIMAMEOptions.selected_modem_bitb_startpoint;
				
			}
			EditableComboBox {
				editable: true;
				hintedmodel: UIMAMEOptions.selectable_modem_bitb_endpoints;
				current-value <=> UIMAMEOptions.selected_modem_bitb_endpoint;
			}
		}
	}

	TitledVerticalBox {
		title: @tr("Other Options");
	
		HorizontalLayout {
			width: 100%;
			padding-bottom: 7px;
			VerticalLayout {
				width: 50%;
				spacing: 5px;
				Switch {
					text: @tr("Skip Info Screen");
					width: 180px;
					height: 28px;
					checked <=> UIMAMEOptions.skip_info_screen;
				}
				Switch {
					text: @tr("Windowed Mode");
					width: 180px;
					height: 28px;
					checked <=> UIMAMEOptions.windowed_mode;
				}
				Switch {
					text: @tr("Disable Mouse Input");
					width: 180px;
					height: 28px;
					checked <=> UIMAMEOptions.disable_mouse_input;
				}
				Switch {
					text: @tr("Disable Sound");
					width: 180px;
					height: 28px;
					checked <=> UIMAMEOptions.disable_sound;
				}
			}

			VerticalLayout {
				width: 50%;
				spacing: 5px;
				Switch {
					text: @tr("Verbose Mode");
					width: 180px;
					height: 28px;
					checked <=> UIMAMEOptions.verbose_mode;
				}
				HorizontalLayout {
					spacing: 0px;
					width: 100%;
					Switch {
						text: @tr("Console Input");
						width: 180px;
						height: 28px;
						checked <=> UIMAMEOptions.console_input;
					}
					EditableComboBox {
						visible: UIMAMEOptions.console_input && UIMAMEOptions.selectable_debug_bitb_startpoints.length > 0;
						enabled: UIMAMEOptions.console_input && UIMAMEOptions.selectable_debug_bitb_startpoints.length > 0;
						height: 33px;
						editable: true;
						hintedmodel: UIMAMEOptions.selectable_debug_bitb_endpoints;
						current-value <=> UIMAMEOptions.selected_debug_bitb_endpoint;
						
					}
				}
				HorizontalLayout {
					spacing: 0px;
					width: 100%;
					Switch {
						text: @tr("Debug Mode");
						width: 180px;
						height: 28px;
						checked <=> UIMAMEOptions.debug_mode;
					}
					EditableComboBox {
						visible: UIMAMEOptions.console_input && UIMAMEOptions.selectable_debug_bitb_startpoints.length > 1;
						enabled: UIMAMEOptions.console_input && UIMAMEOptions.selectable_debug_bitb_startpoints.length > 1;
						height: 33px;
						editable: false;
						hintedmodel: UIMAMEOptions.selectable_debug_bitb_startpoints;
						current-value <=> UIMAMEOptions.selected_debug_bitb_startpoint;
						
					}
				}
				Switch {
					text: @tr("Use Dynamic Recompiler");
					width: 180px;
					height: 28px;
					checked <=> UIMAMEOptions.use_drc;
				}
			}
		}

		EditableComboBox {
			editable: true;
			current-value <=> UIMAMEOptions.custom_options;
			placeholder-text: @tr("Add custom options here");
		}
	}

	VerticalLayout {
		vertical-stretch: 1;
		padding-top: 5px;
		spacing: 5px;
		
		Button {
			text: @tr("Start MAME");
			vertical-stretch: 1;
			primary: true;
			clicked => {
				UIMAMEOptions.start-mame();
			}
		}
	}
}
